---
base_url: https://www.example.org/
title_suffix: ' - example.org'
default_desc: Example site
favicon_paths: ['favicon.ico', 'resources/favicon.png']
apple_touch_icon_path: resources/favicon.png
manifest_path: site.webmanifest
nav_text: Example site
feed_title: example.org
feed_desc: New pages on example.org
logo_path_html: resources/logo-html-*.png
logo_path_amp: resources/logo-amp-*.png
logo_alt: Example.org
nav_toggle_path: resources/chevron-up.svg
nav_toggle_width: 20
nav_toggle_height: 20
menu_button_path: resources/menu.svg
menu_button_width: 20
menu_button_height: 20
dark_button_path: resources/brightness-4.svg
dark_button_width: 20
dark_button_height: 20
author_name: Site Author
author_email: user@example.org
publisher_name: example.org
publisher_logo_path: resources/logo-460.png
extra_static_dirs:
  'extra': other
compress_pages: true
nav_items:
  - name: Welcome
    url: index.html
    id: index
  - name: Cats
    url: cats.html
    id: cats
    children:
      - name: Scottish Fold
        url: scottish_fold.html
        id: scottish
        children:
          - name: Characteristics
            url: scottish_fold.html#chars
          - name: Fame
            url: scottish_fold.html#fame
          - name: Controversy
            url: scottish_fold.html#controversy
      - name: Cheshire
        url: cheshire.html
        id: cheshire
        omit_from_menu: true
  - name: Email me
    url: mailto:user@example.org
