language: go

# The sassc package doesn't appear to be present in Xenial
# (Travis's default Ubuntu version as of 20200529).
dist: bionic

before_install:
  # See https://askubuntu.com/a/1092849.
  - sudo apt-get install nodejs-dev node-gyp libssl1.0-dev
  - sudo apt-get install npm sassc webp yui-compressor
  - npm install -g amphtml-validator

go:
  - 1.x
  - master
